# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amara_auth', '0009_auto_20181129_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', utils.enum.EnumField(enum=utils.enum.Enum(enum_name=b'NotificationType', members=[utils.enum.EnumMember(b'NotificationType', b'ROLE_CHANGED', 'Role changed', 1), utils.enum.EnumMember(b'NotificationType', b'TEAM_INVITATION', 'Team invitation', 2), utils.enum.EnumMember(b'NotificationType', b'NEW_ACTIVE_ASSIGNMENT', 'New active assignment', 3), utils.enum.EnumMember(b'NotificationType', b'REQUEST_UPDATED', 'Request updated', 4), utils.enum.EnumMember(b'NotificationType', b'REQUEST_COMPLETED', 'Request completed by team', 5), utils.enum.EnumMember(b'NotificationType', b'REQUEST_SENDBACK', 'Request sent back to team', 6)]))),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amara_auth.CustomUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lastsentnotification',
            unique_together=set([('user', 'type')]),
        ),
    ]
