# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 17:46
from __future__ import unicode_literals

from django.db import migrations
import utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastsentnotification',
            name='type',
            field=utils.enum.EnumField(enum=utils.enum.Enum(enum_name=b'NotificationType', members=[utils.enum.EnumMember(b'NotificationType', b'ROLE_CHANGED', 'Role changed', 1), utils.enum.EnumMember(b'NotificationType', b'TEAM_INVITATION', 'Team invitation', 2), utils.enum.EnumMember(b'NotificationType', b'NEW_ACTIVE_ASSIGNMENT', 'New active assignment', 3), utils.enum.EnumMember(b'NotificationType', b'REQUEST_UPDATED', 'Request updated', 4), utils.enum.EnumMember(b'NotificationType', b'REQUEST_COMPLETED', 'Request completed by team', 5), utils.enum.EnumMember(b'NotificationType', b'REQUEST_SENDBACK', 'Request sent back to team', 6), utils.enum.EnumMember(b'NotificationType', b'AVAILABLE_ASSIGNMENTS_TRANSCRIPTION', 'Transcription assignment available', 7), utils.enum.EnumMember(b'NotificationType', b'AVAILABLE_ASSIGNMENTS_TRANSLATION', 'Translation assignment available', 8), utils.enum.EnumMember(b'NotificationType', b'AVAILABLE_ASSIGNMENTS_REVIEW', 'Review assignment available', 9), utils.enum.EnumMember(b'NotificationType', b'AVAILABLE_ASSIGNMENTS_APPROVAL', 'Approval assignment available', 10), utils.enum.EnumMember(b'NotificationType', b'AVAILABLE_ASSIGNMENTS_EVALUATION', 'Evaluation assignment available', 11)])),
        ),
    ]
