# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 13:04
from __future__ import unicode_literals

from django.db import migrations
import utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20181024_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notify_request_complete',
            field=utils.enum.EnumField(blank=True, default=utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Request complete'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_request_sent_back',
            field=utils.enum.EnumField(blank=True, default=utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Request sent back'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_request_updated',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Request updated'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_team_role_changed',
            field=utils.enum.EnumField(default=utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), verbose_name='Team role changed'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_visibility',
            field=utils.enum.EnumField(default=utils.enum.EnumMember(b'TeamVisibility', b'PRIVATE', 'Private', 3), enum=utils.enum.Enum(enum_name=b'TeamVisibility', members=[utils.enum.EnumMember(b'TeamVisibility', b'PUBLIC', 'Public', 1), utils.enum.EnumMember(b'TeamVisibility', b'UNLISTED', 'Unlisted', 2), utils.enum.EnumMember(b'TeamVisibility', b'PRIVATE', 'Private', 3)])),
        ),
        migrations.AlterField(
            model_name='team',
            name='video_visibility',
            field=utils.enum.EnumField(default=utils.enum.EnumMember(b'VideoVisibility', b'PRIVATE', 'Private', 3), enum=utils.enum.Enum(enum_name=b'VideoVisibility', members=[utils.enum.EnumMember(b'VideoVisibility', b'PUBLIC', 'Public', 1), utils.enum.EnumMember(b'VideoVisibility', b'UNLISTED', 'Unlisted', 2), utils.enum.EnumMember(b'VideoVisibility', b'PRIVATE', 'Private', 3)])),
        ),
    ]
