# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 08:19
from __future__ import unicode_literals

from django.db import migrations

def generate_subtitles_completed_stat(apps, scheme_editor):
    Team = apps.get_model('teams', 'Team')

    for t in Team.objects.all():
        for tv in t.teamvideo_set.all():
            for sl in tv.video.complete_languages():
                # SubtitleVersion should have information if it completes a SubtitleLanguage
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20181116_1554'),
    ]

    operations = [
    ]
