# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 08:19
from __future__ import unicode_literals

from django.db import migrations

from teams import stats
from utils import dates

def generate_subtitles_completed_stat(apps, scheme_editor):
    Team = apps.get_model('teams', 'Team')

    for t in Team.objects.all():
        for tv in t.teamvideo_set.all():
            for sl in tv.video.complete_languages():
                now = dates.now()
                completion_date = sl.get_tip().created

                if (now - completion_date).days <= stats.DAYS_TO_STORE:
                    stats.increment(tv.team, 'subtitles_completed', completion_date)
                    stats.increment(
                        tv.team,
                        'subtitles_completed-{}'.format(sl.language_code),
                        completion_date)

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20181116_1554'),
    ]

    operations = [
        migrations.RunPython(generate_subtitles_completed_stat)
    ]
