# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 17:48
from __future__ import unicode_literals

from django.db import migrations
import utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_merge_20181119_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notify_approval_assignment',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Approval assignment available'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_evaluation_assignment',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Evaluation assignment available'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_review_assignment',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Review assignment available'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_transcription_assignment',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Transcription assignment available'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_translation_assignment',
            field=utils.enum.EnumField(blank=True, default=None, enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Translation assignment available'),
        ),
        migrations.AlterField(
            model_name='team',
            name='notify_request_complete',
            field=utils.enum.EnumField(blank=True, default=utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), enum=utils.enum.Enum(enum_name=b'TeamNotify', members=[utils.enum.EnumMember(b'TeamNotify', b'ASSIGNEES', 'Assignees', 1), utils.enum.EnumMember(b'TeamNotify', b'CHANGED_MEMBER', 'Changed member', 2), utils.enum.EnumMember(b'TeamNotify', b'MEMBERS', 'All team members', 3), utils.enum.EnumMember(b'TeamNotify', b'MANAGERS', 'Managers', 4), utils.enum.EnumMember(b'TeamNotify', b'ADMINS', 'Admins', 5)]), null=True, verbose_name='Request completed'),
        ),
    ]
